appname = casdoor
httpport = 8444
runmode = prod
copyrequestbody = true
driverName = mysql
dataSourceName = root:Palink@Cas2026!@tcp(127.0.0.1:3306)/
dbName = casdoor
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider =
isCloudIntranet = false
authState = "casdoor"
verificationCodeTimeout = 10
initScore = 0
logPostOnly = true
isUsernameLowered = false
origin = https://104.208.99.17:9443
staticBaseUrl = "https://cdn.casbin.org"
isDemoMode = false
enableGzip = false
logConfig = {"adapter":"file","filename":"logs/casdoor.log","maxdays":30,"perm":"0770"}
