// AUTO-GENERATED by scripts/_p1-split.mjs (P1 机械拆分，逻辑未改动)
// 源: src/components/ui/custom/CharacterCardRenderer.tsx
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import DOMPurify from 'dompurify';
import ReactMarkdown from 'react-markdown';
import { Maximize2, Shield, ShieldCheck, X } from 'lucide-react';
import { cn } from '@/lib/utils';
import type { CharacterSmartCardContext, SillyTavernPluginRuntimeConfig, SmartCardRenderMode } from '@/types';
import { buildSillyTavernCompatRuntimeV2Shim } from '@/components/ui/custom/smart-card-runtime/SillyTavernCompatRuntime';
import { promptInjection } from '@/services/prompt-injection';

import { REMAINING_MARKDOWN_PLUGINS, REMAINING_REHYPE_PLUGINS, INLINE_MIN_HEIGHT, IFRAME_DEFAULT_HEIGHT, IFRAME_INLINE_MAX_HEIGHT, IFRAME_VIEWPORT_MIN_HEIGHT, IFRAME_AVAILABLE_MIN_HEIGHT, SMART_CARD_CSP_NONCE, SMART_CARD_CONTEXT_UPDATE_DELAY_MS, SMART_CARD_VIEWPORT_SETTLE_DELAYS_MS, SMART_CARD_UI_TEXT } from './smart-card-runtime/shared';
import { smartCardRuntimeConfigFallback } from './smart-card-runtime/helpers';
import { SMART_CARD_ASSET_MODE_CHANGED_EVENT } from './smart-card-runtime/asset-mode';
import {
  attachContrastEnhancer,
  isContrastEnhancementEnabled,
  type ContrastEnhancerHandle,
} from './smart-card-runtime/contrast-enhancer';
import type { IframeRenderMode, SmartCardImmersiveTheme, SmartCardViewportContext, SmartCardResourcePlan, SmartCardAction } from './smart-card-runtime/shared';

import { isFullHtmlDocument, htmlUsesViewportHeight, htmlPrefersAvailableHeight, htmlSupportsOuterCollapse, htmlPrefersImmersive, hashSmartCardSource, stableSmartCardStringify, preloadSmartCardRuntimeConfig, getSmartCardBootContextSignature, compactSmartCardChatMessages, readSmartCardTrustGrant, writeSmartCardTrustGrant, getCurrentInterfaceLanguage, isIOSLikeDevice, resolveImmersiveTheme, inferImmersiveThemeFromHtml, estimateIframeInitialHeight, estimateIframeMaxHeight, getLayoutViewportHeight, isSmartCardVisualKeyboardLikelyOpen, collectSmartCardViewportContext, getNearestScrollContainer, getSmartCardAvailableHeight, extractHtmlRenderParts, getHtmlRenderSignature, safeJson, readSmartCardPersistedStorage, applySmartCardStoragePatch, adaptSmartCardRuntimeAccess, normalizeSmartCardScriptBlocks, addSmartCardScriptNonce, optimizeSmartCardHtmlForRuntime, buildSmartCardResourcePlan, mergeSmartCardResourcePlans, buildSillyTavernPluginResourcePlan, buildSmartCardResourceHints, scheduleSmartCardResourceWarmup, buildSmartCardAdapterStyle, resolveHtmlRenderMode, toSmartCardRuntimeMode, prepareInlineHtml, buildShim } from './smart-card-runtime/helpers';
import { getSmartCardPluginScriptBundle, getSmartCardPluginSourceKey, slimSmartCardPluginScriptBundle } from './smart-card-runtime/primitives';
import { SMART_CARD_RUNTIME_URL } from './smart-card-runtime/runtime-url';

export { looksLikeSmartCardHtml, looksLikeRenderableCardHtml } from './smart-card-runtime/helpers';
export type { SmartCardInspectTarget, SmartCardAction } from './smart-card-runtime/shared';

function injectIntoFullDocument(
  html: string,
  shim: string,
  frameId: string,
  resourcePlan: SmartCardResourcePlan,
  customCss?: string,
  includeImmersiveBridge = false,
): string {
  const css = customCss ? `<style>${customCss}</style>` : '';
  const adapterCss = buildSmartCardAdapterStyle(html);
  const resourceHints = buildSmartCardResourceHints(resourcePlan);
  const immersiveBridge = includeImmersiveBridge ? buildSmartCardImmersiveBridge(frameId) : '';
  let result = html;
  if (/<head[\s>]/i.test(result)) {
    result = result.replace(/<head([^>]*)>/i, (_match, attrs = '') => `<head${attrs}><meta charset="UTF-8">${resourceHints}${shim}${immersiveBridge}`);
  } else {
    result = result.replace(/<html([^>]*)>/i, (_match, attrs = '') => `<html${attrs}><head><meta charset="UTF-8">${resourceHints}${shim}${immersiveBridge}</head>`);
  }
  if (/<\/head\s*>/i.test(result)) {
    result = result.replace(/<\/head\s*>/i, `${css}${adapterCss}</head>`);
  }
  if (!/<html[\s>]/i.test(result)) {
    return `<!DOCTYPE html><html><head><meta charset="UTF-8">${resourceHints}${shim}${immersiveBridge}${css}${adapterCss}</head><body>${result}</body></html>`;
  }
  return result;
}

function wrapHtmlFragment(
  fragment: string,
  shim: string,
  frameId: string,
  resourcePlan: SmartCardResourcePlan,
  customCss?: string,
  includeImmersiveBridge = false,
): string {
  const css = customCss ? `<style>${customCss}</style>` : '';
  const adapterCss = buildSmartCardAdapterStyle(fragment);
  const resourceHints = buildSmartCardResourceHints(resourcePlan);
  const immersiveBridge = includeImmersiveBridge ? buildSmartCardImmersiveBridge(frameId) : '';
  return `<!DOCTYPE html><html><head><meta charset="UTF-8">${resourceHints}${shim}${immersiveBridge}<style>html,body{width:100%;margin:0;padding:0;background:transparent;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;}body{box-sizing:border-box;overflow-y:auto;overflow-x:hidden;}</style>${css}</head><body>${fragment}${adapterCss}</body></html>`;
}

interface IframeRendererProps {
  html: string;
  isFullDocument: boolean;
  customCss?: string;
  className?: string;
  context: CharacterSmartCardContext;
  mode: IframeRenderMode;
  onAction?: (action: SmartCardAction) => void;
}

const IframeRenderer = React.memo(function IframeRenderer({
  html,
  isFullDocument,
  customCss,
  className,
  context,
  mode,
  onAction,
}: IframeRendererProps) {
  const frameIdRef = useRef(`palink-smart-card-${Math.random().toString(36).slice(2)}-${Date.now()}`);
  const iframeRef = useRef<HTMLIFrameElement | null>(null);
  const wrapperRef = useRef<HTMLDivElement | null>(null);
  const lastPostedContextSignatureRef = useRef('');
  // [P0-SRCDOC-SLIM] 最近一次推送给当前 iframe 的插件脚本包版本（generated_at）。
  // 相同版本不重复推送；iframe 重建/重载后主动请求（request-plugin-scripts）时强制重推。
  const lastPushedPluginBundleVersionRef = useRef<string | null>(null);
  const pendingContextUpdateRef = useRef<CharacterSmartCardContext | null>(null);
  const contextUpdateTimerRef = useRef<number | null>(null);
  const stableViewportSizeRef = useRef({
    width: typeof window !== 'undefined' ? (window.innerWidth || window.visualViewport?.width || 390) : 390,
    height: typeof window !== 'undefined' ? (window.innerHeight || window.visualViewport?.height || 760) : 760,
  });
  const frameFocusedEditableRef = useRef(false);
  // [STATUSBAR-HEIGHT] 记录最后一次收到 iframe postMessage resize 上报的时间戳，
  // 用于判断 postMessage 主通道是否活跃（活跃时轮询兜底不介入，避免两通道互相打架）。
  const lastResizeSignalAtRef = useRef(0);
  // [CONTRAST-ENHANCE] 亮色模式对比度增强：作用于本 iframe 内（非沉浸式全屏）卡片文本。
  const contrastEnhancerRef = useRef<ContrastEnhancerHandle | null>(null);
  // 显式要求内联渲染时（状态栏卡片由 Message.tsx 传入 presentationMode:'inline'），
  // 压过所有"沉浸式/全屏/可折叠"启发式——状态栏应像 ST 那样内联在聊天气泡里、始终可见、随 AI 输出刷新。
  const explicitInline = context?.presentationMode === 'inline';
  // [FULLSCREEN-ADAPT] vh 布局判定不再被 explicitInline 短路：状态栏/界面文档
  // （如 launcher{height:96vh}、main-container{height:calc(100vh-20px)}）在内容测量
  // 模式下 100vh=iframe 高度，会被压缩或形成正反馈；按可用高度渲染（iframe 高度=
  // 消息区域可用空间）才能正确显示，对齐 ST 中此类界面原样渲染在页面视口上的效果。
  const prefersAvailableHeight = useMemo(
    () => htmlPrefersAvailableHeight(html),
    [html],
  );
  const initialHeight = useMemo(() => {
    if (prefersAvailableHeight && typeof window !== 'undefined') {
      return getSmartCardAvailableHeight(null);
    }
    if (explicitInline) {
      // 状态栏等内联面板完全由内容驱动：初始高用保守估算（≈折叠态 header），
      // 避免 htmlUsesViewportHeight 把初始高/最小高推到 ~0.68 视口（展开被截断、折叠留白、闪烁）。
      // 真实高度由 iframe 内 measure() 上报的 body 文档流高度决定，会立即校正。
      return IFRAME_DEFAULT_HEIGHT;
    }
    return estimateIframeInitialHeight(html);
  }, [html, prefersAvailableHeight, explicitInline]);
  const maxMeasuredHeight = useMemo(
    () => estimateIframeMaxHeight(html, initialHeight),
    [html, initialHeight]
  );
  const minMeasuredHeight = useMemo(
    // 内联面板不能受 htmlUsesViewportHeight 视口启发式影响——那会把 iframe 的最小高锁到 ~0.68 视口，
    // 折叠时留下大段空白、展开测量回落时被 min-height 截断。内联面板必须允许高度自由收缩到折叠态 header。
    () => (explicitInline ? INLINE_MIN_HEIGHT : (prefersAvailableHeight || htmlUsesViewportHeight(html) ? initialHeight : INLINE_MIN_HEIGHT)),
    [html, initialHeight, prefersAvailableHeight, explicitInline]
  );
  const [availableHeight, setAvailableHeight] = useState(initialHeight);
  const [height, setHeight] = useState(initialHeight);
  const stableAvailableHeightRef = useRef(initialHeight);
  const htmlResourcePlan = useMemo(
    () => buildSmartCardResourcePlan(`${html}\n${customCss || ''}`),
    [html, customCss]
  );
  const supportsOuterCollapse = useMemo(
    () => (explicitInline ? false : htmlSupportsOuterCollapse(html)),
    [html, explicitInline],
  );
  const prefersImmersive = useMemo(
    () => (explicitInline ? false : htmlPrefersImmersive(html)),
    [html, explicitInline],
  );
  const isIOSDevice = useMemo(() => isIOSLikeDevice(), []);
  const [viewportContext, setViewportContext] = useState<SmartCardViewportContext>(() => (
    collectSmartCardViewportContext(null, {
      isIOSDevice,
      prefersImmersive,
      prefersAvailableHeight,
      availableHeight: initialHeight,
      stableViewportHeight: stableViewportSizeRef.current.height,
      frameFocusedEditable: frameFocusedEditableRef.current,
    })
  ));
  const sourceFingerprint = useMemo(
    () => hashSmartCardSource(`${html}\n${customCss || ''}`),
    [html, customCss]
  );
  const [collapsed, setCollapsed] = useState(false);
  const [trustedNative, setTrustedNative] = useState(() => (
    mode === 'trusted-native' || readSmartCardTrustGrant(context.characterId, sourceFingerprint)
  ));
  const [pendingTrustAction, setPendingTrustAction] = useState<'enable' | 'revoke' | null>(null);
  const inferredImmersiveTheme = useMemo(
    () => inferImmersiveThemeFromHtml(html, customCss),
    [html, customCss]
  );
  const [immersiveTheme, setImmersiveTheme] = useState<SmartCardImmersiveTheme>(() => inferredImmersiveTheme);
  const effectiveMode: IframeRenderMode = trustedNative ? 'trusted-native' : mode;
  const interfaceLanguage = getCurrentInterfaceLanguage();
  const smartCardText = SMART_CARD_UI_TEXT[interfaceLanguage];
  const [stPluginRuntimeConfig, setStPluginRuntimeConfig] = useState<SillyTavernPluginRuntimeConfig | null>(() => smartCardRuntimeConfigFallback);
  // 资源计划必须对 stPluginRuntimeConfig 的「异步晚到」保持稳定：
  // preloadSmartCardRuntimeConfig 在首帧后才返回，若把它纳入 resourcePlan 依赖，
  // 晚到会重建 srcDoc → iframe 整页重载 → 在途字体/CSS 请求被中止（net::ERR_ABORTED）
  // + 高度测量在字体未加载时算小 →“先截断、点一下才多展开”。
  // 因此这里用 ref 快照每个角色首帧抓到的 config；晚到的真实 config 仍会经
  // postContextToFrame 的 context-update postMessage 热更新进 iframe，不重建文档。
  const resourcePlanConfigRef = useRef<SillyTavernPluginRuntimeConfig | null | undefined>(smartCardRuntimeConfigFallback);
  const resourcePlan = useMemo(
    () => mergeSmartCardResourcePlans(htmlResourcePlan, buildSillyTavernPluginResourcePlan(resourcePlanConfigRef.current)),
    [htmlResourcePlan, context.characterId, sourceFingerprint]
  );
  const resolvedImmersiveTheme = useMemo(
    () => resolveImmersiveTheme(immersiveTheme),
    [immersiveTheme]
  );
  const immersiveToolbarTextColor = resolvedImmersiveTheme.isDark ? 'rgba(255,255,255,0.96)' : 'rgba(15,23,42,0.92)';
  const immersiveToolbarButtonBackground = resolvedImmersiveTheme.isDark ? 'rgba(0,0,0,0.3)' : 'rgba(255,255,255,0.42)';
  const immersiveToolbarButtonBorder = resolvedImmersiveTheme.isDark ? 'rgba(255,255,255,0.16)' : 'rgba(15,23,42,0.08)';
  const immersiveToolbarBackdrop = resolvedImmersiveTheme.isDark ? 'blur(18px) saturate(140%)' : 'blur(18px) saturate(160%)';
  const immersiveTopInsetPx = isIOSDevice ? 'max(env(safe-area-inset-top), 48px)' : 'env(safe-area-inset-top, 0px)';
  const presentationMode: CharacterSmartCardContext['presentationMode'] = explicitInline
    ? 'inline'
    : prefersImmersive
      ? (trustedNative ? 'immersive-trusted-native' : 'immersive-sandbox')
      : 'inline';
  const persistedStorage = useMemo(
    () => readSmartCardPersistedStorage(context, sourceFingerprint),
    [context.characterId, context.sessionId, sourceFingerprint]
  );
  useEffect(() => {
    let cancelled = false;
    preloadSmartCardRuntimeConfig().then((config) => {
      if (!cancelled) setStPluginRuntimeConfig(config);
    });
    return () => { cancelled = true; };
  }, [context.characterId]);
  // 角色切换时重置资源计划快照，避免沿用上个角色的 config；异步晚到不会重建 srcDoc。
  useEffect(() => {
    resourcePlanConfigRef.current = smartCardRuntimeConfigFallback;
  }, [context.characterId, sourceFingerprint]);
  // 智能卡资源模式（direct/proxy）切换时重建 srcDoc：URL 改写结果不同
  //（optimizeSmartCardHtmlForRuntime 的缓存键已含模式，这里只需触发重算）
  const [assetModeVersion, setAssetModeVersion] = useState(0);
  useEffect(() => {
    const handler = () => setAssetModeVersion((v) => v + 1);
    window.addEventListener(SMART_CARD_ASSET_MODE_CHANGED_EVENT, handler);
    return () => window.removeEventListener(SMART_CARD_ASSET_MODE_CHANGED_EVENT, handler);
  }, []);
  const compactedChatMessages = useMemo(
    () => compactSmartCardChatMessages(context.chatMessages, context.messageIndex),
    [context.chatMessages, context.messageIndex],
  );
  const liveContext = useMemo<CharacterSmartCardContext>(() => ({
    characterId: context.characterId,
    characterName: context.characterName,
    userName: context.userName,
    language: context.language || interfaceLanguage,
    messageId: context.messageId,
    messageIndex: context.messageIndex,
    messageContent: context.messageContent,
    chatMessages: compactedChatMessages,
    persistedStorage,
    firstMes: context.firstMes,
    alternateGreetings: context.alternateGreetings,
    characterExtensions: context.characterExtensions,
    presetData: context.presetData,
    globalRegexScripts: context.globalRegexScripts,
    stPluginRuntimeConfig,
    sessionId: context.sessionId,
    depth: context.depth,
    isInit: context.isInit,
    presentationMode,
    trustedNative,
    sourceFingerprint,
    viewport: viewportContext,
    variables: context.variables,
  }), [
    context.characterId,
    context.characterName,
    context.userName,
    context.language,
    interfaceLanguage,
    context.messageId,
    context.variables,
    context.messageIndex,
    context.messageContent,
    compactedChatMessages,
    context.firstMes,
    context.alternateGreetings,
    context.characterExtensions,
    context.presetData,
    context.globalRegexScripts,
    stPluginRuntimeConfig,
    context.sessionId,
    context.depth,
    context.isInit,
    persistedStorage,
    presentationMode,
    sourceFingerprint,
    trustedNative,
    viewportContext,
  ]);

  const bootContextSignature = getSmartCardBootContextSignature(
    { ...context, stPluginRuntimeConfig },
    interfaceLanguage,
    persistedStorage,
    sourceFingerprint,
    presentationMode,
    trustedNative,
  );

  const bootContext = useMemo<CharacterSmartCardContext>(() => ({
    characterId: context.characterId,
    characterName: context.characterName,
    userName: context.userName,
    language: context.language || interfaceLanguage,
    messageId: undefined,
    messageIndex: undefined,
    messageContent: '',
    chatMessages: [],
    persistedStorage,
    firstMes: context.firstMes,
    alternateGreetings: context.alternateGreetings,
    characterExtensions: context.characterExtensions,
    presetData: context.presetData,
    globalRegexScripts: context.globalRegexScripts,
    stPluginRuntimeConfig,
    sessionId: context.sessionId,
    depth: 0,
    isInit: false,
    presentationMode,
    trustedNative,
    sourceFingerprint,
    viewport: viewportContext,
    variables: context.variables,
  }), [
    context.characterId,
    context.characterName,
    context.userName,
    context.language,
    interfaceLanguage,
    bootContextSignature,
    stPluginRuntimeConfig,
  ]);

  useEffect(() => {
    setTrustedNative(mode === 'trusted-native' || readSmartCardTrustGrant(context.characterId, sourceFingerprint));
    setPendingTrustAction(null);
  }, [context.characterId, mode, sourceFingerprint]);

  useEffect(() => {
    setImmersiveTheme(inferredImmersiveTheme);
  }, [inferredImmersiveTheme, sourceFingerprint]);

  const srcDoc = useMemo(() => {
    const legacyShim = buildShim(bootContext, frameIdRef.current);
    const compatV2Shim = buildSillyTavernCompatRuntimeV2Shim({
      context: bootContext,
      frameId: frameIdRef.current,
      sourceHtml: `${html}\n${customCss || ''}`,
      mode: toSmartCardRuntimeMode(effectiveMode),
      nonce: SMART_CARD_CSP_NONCE,
      origin: typeof window !== 'undefined' && window.location ? window.location.origin : 'http://localhost:3000',
      // [P1-SHIM-EXTERNAL] 外部运行时资产可用时用 <script src> 引用（跨卡复用 V8 code cache），
      // 否则回退为全内联（旧行为）。
      externalRuntimeUrl: SMART_CARD_RUNTIME_URL,
    });
    const shim = `${legacyShim}${compatV2Shim}`;
    const sourceHtml = effectiveMode === 'static-html'
      ? DOMPurify.sanitize(html, {
          ADD_TAGS: ['style', 'link', 'meta', 'div', 'span', 'font', 'center', 'marquee', 'hr', 'br', 'details', 'summary', 'img', 'table', 'thead', 'tbody', 'tr', 'th', 'td', 'video', 'audio', 'source', 'iframe', 'button', 'input', 'select', 'option', 'textarea', 'section', 'main', 'article'],
          ADD_ATTR: ['class', 'style', 'color', 'bgcolor', 'align', 'valign', 'data-*', 'href', 'src', 'alt', 'target', 'rel', 'width', 'height', 'controls', 'autoplay', 'loop', 'muted', 'poster', 'preload', 'type', 'value', 'name', 'placeholder', 'disabled', 'readonly', 'checked', 'selected'],
        })
      : html;
    const adaptedHtml = effectiveMode === 'iframe-js' ? adaptSmartCardRuntimeAccess(sourceHtml) : sourceHtml;
    const runtimeHtml = optimizeSmartCardHtmlForRuntime(adaptedHtml);
    const normalizedHtml = effectiveMode === 'iframe-js' || effectiveMode === 'trusted-native'
      ? addSmartCardScriptNonce(normalizeSmartCardScriptBlocks(runtimeHtml))
      : runtimeHtml;
    const finalDoc = isFullDocument
      ? injectIntoFullDocument(normalizedHtml, shim, frameIdRef.current, resourcePlan, customCss, prefersImmersive)
      : wrapHtmlFragment(normalizedHtml, shim, frameIdRef.current, resourcePlan, customCss, prefersImmersive);

    return finalDoc;
    // 注意：srcDoc 只依赖「内容」变化（html/customCss/effectiveMode/resourcePlan），
    // 刻意排除 bootContextSignature —— 硬刷新时 characterExtensions / globalRegexScripts /
    // stPluginRuntimeConfig 会晚于首帧到达，若把它纳入依赖，每次晚到都会触发 srcDoc 重建
    // → iframe 整页重载 → 在途资源中止（ERR_ABORTED 噪音）+ 高度闪烁（“一跳一跳”）。
    // 运行时上下文（含 variables/characterExtensions）已由 postContextToFrame 的
    // context-update postMessage 通道热更新进 iframe（见 handleMessage context-update 分支），
    // 无需重建文档；真正的内容变化由 sourceFingerprint / html 表达。
    // assetModeVersion 例外：资源模式切换改变 URL 改写结果，必须重建。
  }, [html, isFullDocument, customCss, effectiveMode, prefersImmersive, resourcePlan, assetModeVersion]);

  // [P0-SRCDOC-SLIM] 把插件脚本包（js/modules 源码）单次推送给 iframe。
  // [P1-SRCDOC-SLIM] 推送的是「清单」：仅元数据 + source URL（剥离 content），
  // iframe 按需经 getPluginScriptContents 批量取内容（父侧走 HTTP/内存缓存）。
  // force=true（iframe 重建/重载后主动请求）时忽略版本去重强制重推；
  // 否则仅在 generated_at 变化时推送，避免 context 高频更新时重复传输大包。
  const postPluginScriptsToFrame = useCallback((targetWindow: Window | null, force = false) => {
    if (!targetWindow) return;
    const bundle = getSmartCardPluginScriptBundle();
    if (!bundle || !Array.isArray(bundle.scripts) || bundle.scripts.length === 0) return;
    const version = String(bundle.generated_at || '');
    if (!force && lastPushedPluginBundleVersionRef.current === version) return;
    lastPushedPluginBundleVersionRef.current = version;
    targetWindow.postMessage({
      source: 'palink-smart-card-parent',
      frameId: frameIdRef.current,
      type: 'plugin-scripts-push',
      bundle: slimSmartCardPluginScriptBundle(bundle),
    }, '*');
  }, []);

  const postContextToFrame = useCallback((nextContext: CharacterSmartCardContext, immediate = false) => {
    const targetWindow = iframeRef.current?.contentWindow;
    if (!targetWindow) return;

    const postNow = (contextToPost: CharacterSmartCardContext) => {
      const signature = stableSmartCardStringify(contextToPost);
      if (signature === lastPostedContextSignatureRef.current) return;
      lastPostedContextSignatureRef.current = signature;
      targetWindow.postMessage({
        source: 'palink-smart-card-parent',
        frameId: frameIdRef.current,
        type: 'context-update',
        context: contextToPost,
      }, '*');
      // [P0-SRCDOC-SLIM] context 发送时顺带把插件脚本包推给 iframe（幂等，按
      // generated_at 去重）。源码不再内联进 context，避免 4.4MB 随每次
      // context-update（滚动/键盘等高频触发）反复结构化克隆导致滑动卡顿。
      postPluginScriptsToFrame(targetWindow);
    };

    if (immediate) {
      if (contextUpdateTimerRef.current != null && typeof window !== 'undefined') {
        window.clearTimeout(contextUpdateTimerRef.current);
        contextUpdateTimerRef.current = null;
      }
      pendingContextUpdateRef.current = null;
      postNow(nextContext);
      return;
    }

    pendingContextUpdateRef.current = nextContext;
    if (contextUpdateTimerRef.current != null || typeof window === 'undefined') {
      if (typeof window === 'undefined') postNow(nextContext);
      return;
    }
    contextUpdateTimerRef.current = window.setTimeout(() => {
      contextUpdateTimerRef.current = null;
      const pendingContext = pendingContextUpdateRef.current;
      pendingContextUpdateRef.current = null;
      if (pendingContext) postNow(pendingContext);
    }, SMART_CARD_CONTEXT_UPDATE_DELAY_MS);
  }, [postPluginScriptsToFrame]);

  useEffect(() => {
    postContextToFrame(liveContext);
  }, [liveContext, postContextToFrame]);

  useEffect(() => () => {
    if (contextUpdateTimerRef.current != null && typeof window !== 'undefined') {
      window.clearTimeout(contextUpdateTimerRef.current);
      contextUpdateTimerRef.current = null;
    }
    pendingContextUpdateRef.current = null;
    // [CONTRAST-ENHANCE] iframe 卸载时释放对比度增强器（observer + 覆盖还原）
    contrastEnhancerRef.current?.dispose();
    contrastEnhancerRef.current = null;
    // [EP-BRIDGE] iframe 卸载时清理其在 promptInjection 中的扩展提示词 source，
    // 避免关闭全屏/切换角色后残留污染后续生成。
    try {
      promptInjection.removeSource(`frame:${frameIdRef.current}`);
    } catch { /* ignore */ }
  }, []);

  // [CONTRAST-ENHANCE] 设置页开关切换 → 立即重判（注入/清除）
  useEffect(() => {
    const handleContrastToggle = () => {
      contrastEnhancerRef.current?.run();
    };
    window.addEventListener('palink-auto-contrast-changed', handleContrastToggle);
    return () => window.removeEventListener('palink-auto-contrast-changed', handleContrastToggle);
  }, []);

  const postLiveContext = useCallback(() => {
    postContextToFrame(liveContext, true);
  }, [liveContext, postContextToFrame]);

  // [CONTRAST-ENHANCE] iframe onLoad：同源直接读 contentDocument 并挂载对比度增强器。
  // 仅增强非沉浸式全屏卡片（launcher 等全屏界面自带完整配色，不套用消息气泡背景判定）。
  const handleFrameLoad = useCallback(() => {
    postLiveContext();
    // [P0-SRCDOC-SLIM] iframe onload（已稳定）时强制推送插件脚本包。
    // 解析期由 shim 发出的 request-plugin-scripts 触发的推送可能在 srcDoc 后续
    // 更新 / iframe 重新导航时被丢弃（刷新页面冷启动场景实测丢失），onload 时
    // iframe 已加载完成，此处推送确保 bundle 必达。iframe 内按 generated_at
    // 幂等，重复推送无害。
    postPluginScriptsToFrame(iframeRef.current?.contentWindow ?? null, true);
    const frame = iframeRef.current;
    const frameDoc = frame?.contentDocument;
    if (!frameDoc || frameDoc === document || prefersImmersive) return;
    if (contrastEnhancerRef.current) {
      contrastEnhancerRef.current.dispose();
      contrastEnhancerRef.current = null;
    }
    const container = frameDoc.body || (frameDoc.documentElement as HTMLElement | null);
    if (!container) return;
    contrastEnhancerRef.current = attachContrastEnhancer({
      container,
      doc: frameDoc,
      themeRoot: document.documentElement,
      isEnabled: isContrastEnhancementEnabled,
    });
  }, [postLiveContext, postPluginScriptsToFrame, prefersImmersive]);

  const updateViewportContext = useCallback((nextAvailableHeight = availableHeight) => {
    if (typeof window !== 'undefined') {
      const visualHeight = window.visualViewport?.height || 0;
      const innerHeight = window.innerHeight || 0;
      const visualWidth = window.visualViewport?.width || 0;
      const innerWidth = window.innerWidth || 0;
      const keyboardLooksOpen = isSmartCardVisualKeyboardLikelyOpen(
        stableViewportSizeRef.current.height,
        frameFocusedEditableRef.current,
      );
      if (!keyboardLooksOpen) {
        // [FULLSCREEN-ADAPT] 稳定视口高取实际视口高度（视觉/布局视口取大者），
        // 兜底用 IFRAME_VIEWPORT_MIN_HEIGHT(320) 而非硬编码 760——原 760 在小视口
        // （如窗口高度 <600 或移动端）下会把沉浸式全屏覆盖层撑到 760px，
        // 超出视口导致底部被裁剪。
        const settledHeight = Math.max(visualHeight || 0, innerHeight || 0, IFRAME_VIEWPORT_MIN_HEIGHT);
        const settledWidth = Math.max(visualWidth || 0, innerWidth || 0, 320);
        stableViewportSizeRef.current = {
          width: settledWidth,
          height: settledHeight,
        };
      } else {
        // P2-2（问题 6）: 键盘弹出时覆盖层高度收缩到视觉视口（键盘上方剩余空间），
        // 不再跳过更新——此前固定高度覆盖层会遮挡键盘输入区。保留最小高兜底。
        // 可用高度场景（prefersAvailableHeight）仍由 updateAvailableHeight 锁定
        // 策略管理，此处只处理沉浸式/内容测量场景。
        const settledHeight = Math.max(visualHeight || 0, IFRAME_VIEWPORT_MIN_HEIGHT);
        const settledWidth = Math.max(visualWidth || 0, innerWidth || 0, 320);
        stableViewportSizeRef.current = {
          width: settledWidth,
          height: settledHeight,
        };
      }
    }
    const nextViewport = collectSmartCardViewportContext(wrapperRef.current, {
      isIOSDevice,
      prefersImmersive,
      prefersAvailableHeight,
      availableHeight: nextAvailableHeight,
      stableViewportHeight: stableViewportSizeRef.current.height,
      frameFocusedEditable: frameFocusedEditableRef.current,
    });
    setViewportContext((current) => {
      if (stableSmartCardStringify(current) === stableSmartCardStringify(nextViewport)) return current;
      return nextViewport;
    });
  }, [availableHeight, isIOSDevice, prefersAvailableHeight, prefersImmersive]);

  useEffect(() => scheduleSmartCardResourceWarmup(resourcePlan), [resourcePlan]);

  useEffect(() => {
    if (prefersAvailableHeight) {
      stableAvailableHeightRef.current = initialHeight;
      setAvailableHeight(initialHeight);
      setHeight(initialHeight);
      return;
    }
    // 内联面板最小高只保底到 INLINE_MIN_HEIGHT，绝不抬回 initialHeight（否则折叠态会被撑开留白）。
    const floor = explicitInline ? INLINE_MIN_HEIGHT : initialHeight;
    setHeight((current) => Math.max(current, floor));
  }, [initialHeight, prefersAvailableHeight, sourceFingerprint, explicitInline]);

  const updateAvailableHeight = useCallback(() => {
    if (!prefersAvailableHeight) return;
    const keyboardLooksOpen = isSmartCardVisualKeyboardLikelyOpen(
      stableViewportSizeRef.current.height,
      frameFocusedEditableRef.current,
    );
    if (keyboardLooksOpen && stableAvailableHeightRef.current > 0) {
      const lockedHeight = stableAvailableHeightRef.current;
      setAvailableHeight(lockedHeight);
      setHeight(lockedHeight);
      updateViewportContext(lockedHeight);
      return;
    }
    const nextHeight = getSmartCardAvailableHeight(wrapperRef.current, stableViewportSizeRef.current.height);
    stableAvailableHeightRef.current = nextHeight;
    setAvailableHeight(nextHeight);
    setHeight(nextHeight);
    updateViewportContext(nextHeight);
  }, [prefersAvailableHeight, updateViewportContext]);

  const settleViewportContext = useCallback(() => {
    if (typeof window === 'undefined') return;
    SMART_CARD_VIEWPORT_SETTLE_DELAYS_MS.forEach((delay) => {
      window.setTimeout(() => {
        if (prefersAvailableHeight) {
          updateAvailableHeight();
        } else {
          updateViewportContext();
        }
      }, delay);
    });
  }, [prefersAvailableHeight, updateAvailableHeight, updateViewportContext]);

  useEffect(() => {
    if (!prefersAvailableHeight || typeof window === 'undefined') return;

    let animationFrame = 0;
    const scheduleUpdate = () => {
      if (animationFrame) window.cancelAnimationFrame(animationFrame);
      animationFrame = window.requestAnimationFrame(() => {
        animationFrame = 0;
        updateAvailableHeight();
      });
    };

    scheduleUpdate();
    const timers = [
      window.setTimeout(scheduleUpdate, 80),
      window.setTimeout(scheduleUpdate, 350),
    ];
    window.addEventListener('resize', scheduleUpdate);
    window.addEventListener('orientationchange', scheduleUpdate);
    window.addEventListener('focus', scheduleUpdate);
    window.addEventListener('blur', scheduleUpdate);
    window.addEventListener('pageshow', scheduleUpdate);
    document.addEventListener('visibilitychange', scheduleUpdate);
    document.addEventListener('focusin', scheduleUpdate);
    document.addEventListener('focusout', scheduleUpdate);
    window.visualViewport?.addEventListener('resize', scheduleUpdate);
    window.visualViewport?.addEventListener('scroll', scheduleUpdate);

    const resizeObserver = typeof ResizeObserver !== 'undefined'
      ? new ResizeObserver(scheduleUpdate)
      : null;
    if (resizeObserver) {
      if (wrapperRef.current) resizeObserver.observe(wrapperRef.current);
      const composer = document.querySelector<HTMLElement>('[data-palink-chat-composer="true"]');
      if (composer) resizeObserver.observe(composer);
      const scrollContainer = getNearestScrollContainer(wrapperRef.current);
      if (scrollContainer) resizeObserver.observe(scrollContainer);
    }

    return () => {
      if (animationFrame) window.cancelAnimationFrame(animationFrame);
      timers.forEach((timer) => window.clearTimeout(timer));
      window.removeEventListener('resize', scheduleUpdate);
      window.removeEventListener('orientationchange', scheduleUpdate);
      window.removeEventListener('focus', scheduleUpdate);
      window.removeEventListener('blur', scheduleUpdate);
      window.removeEventListener('pageshow', scheduleUpdate);
      document.removeEventListener('visibilitychange', scheduleUpdate);
      document.removeEventListener('focusin', scheduleUpdate);
      document.removeEventListener('focusout', scheduleUpdate);
      window.visualViewport?.removeEventListener('resize', scheduleUpdate);
      window.visualViewport?.removeEventListener('scroll', scheduleUpdate);
      resizeObserver?.disconnect();
    };
  }, [prefersAvailableHeight, updateAvailableHeight]);

  useEffect(() => {
    if (prefersAvailableHeight || typeof window === 'undefined') return;

    let animationFrame = 0;
    const scheduleUpdate = () => {
      if (animationFrame) window.cancelAnimationFrame(animationFrame);
      animationFrame = window.requestAnimationFrame(() => {
        animationFrame = 0;
        updateViewportContext();
      });
    };

    scheduleUpdate();
    const timers = [
      window.setTimeout(scheduleUpdate, 80),
      window.setTimeout(scheduleUpdate, 350),
    ];
    window.addEventListener('resize', scheduleUpdate);
    window.addEventListener('orientationchange', scheduleUpdate);
    window.addEventListener('focus', scheduleUpdate);
    window.addEventListener('blur', scheduleUpdate);
    window.addEventListener('pageshow', scheduleUpdate);
    document.addEventListener('visibilitychange', scheduleUpdate);
    document.addEventListener('focusin', scheduleUpdate);
    document.addEventListener('focusout', scheduleUpdate);
    window.visualViewport?.addEventListener('resize', scheduleUpdate);
    window.visualViewport?.addEventListener('scroll', scheduleUpdate);

    const resizeObserver = typeof ResizeObserver !== 'undefined'
      ? new ResizeObserver(scheduleUpdate)
      : null;
    if (resizeObserver) {
      if (wrapperRef.current) resizeObserver.observe(wrapperRef.current);
      const composer = document.querySelector<HTMLElement>('[data-palink-chat-composer="true"]');
      if (composer) resizeObserver.observe(composer);
    }

    return () => {
      if (animationFrame) window.cancelAnimationFrame(animationFrame);
      timers.forEach((timer) => window.clearTimeout(timer));
      window.removeEventListener('resize', scheduleUpdate);
      window.removeEventListener('orientationchange', scheduleUpdate);
      window.removeEventListener('focus', scheduleUpdate);
      window.removeEventListener('blur', scheduleUpdate);
      window.removeEventListener('pageshow', scheduleUpdate);
      document.removeEventListener('visibilitychange', scheduleUpdate);
      document.removeEventListener('focusin', scheduleUpdate);
      document.removeEventListener('focusout', scheduleUpdate);
      window.visualViewport?.removeEventListener('resize', scheduleUpdate);
      window.visualViewport?.removeEventListener('scroll', scheduleUpdate);
      resizeObserver?.disconnect();
    };
  }, [prefersAvailableHeight, updateViewportContext]);

  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
      const data = event.data;
      // frame-error/frame-csp：shim 错误上报使用 source 'palink-smart-card-frame'（历史
      // 命名），此前被 'palink-smart-card' 过滤静默丢弃 → 卡内脚本错误（跨源访问/初始化
      // 失败等）在主控制台不可见，排查只能盲猜。现将这类消息记录到
      // window.__palinkFrameErrors（调试用，上限 50 条）并 console.error 输出。
      if (data && data.source === 'palink-smart-card-frame' && frameIdRef.current && data.frameId === frameIdRef.current) {
        if (data.type === 'frame-error' || data.type === 'frame-csp') {
          const entry = { frameId: frameIdRef.current, type: data.type, message: data.message, directive: data.directive, blockedURI: data.blockedURI, at: Date.now() };
          try {
            const w = window as unknown as { __palinkFrameErrors?: unknown[] };
            w.__palinkFrameErrors = w.__palinkFrameErrors || [];
            if (w.__palinkFrameErrors.length < 50) w.__palinkFrameErrors.push(entry);
          } catch { /* ignore */ }
          console.error(`[smart-card ${frameIdRef.current.slice(0, 8)}] 卡内错误:`, data.message || data);
        }
        return;
      }
      if (!data || data.source !== 'palink-smart-card' || data.frameId !== frameIdRef.current) return;
      // [RESIZE-DEBUG] 记录 iframe → 父页面消息类型（排查 resize 不达）：截断问题时
      // 看该序列里有没有 resize / 其高度值。上限 80 条，仅诊断用。
      try {
        const w2 = window as unknown as { __palinkFrameMsgs?: Array<Record<string, unknown>> };
        w2.__palinkFrameMsgs = w2.__palinkFrameMsgs || [];
        if (w2.__palinkFrameMsgs.length < 80) {
          w2.__palinkFrameMsgs.push({ frameId: String(data.frameId || '').slice(-6), type: data.type, height: data.height, realContent: data.realContent });
        }
      } catch { /* ignore */ }
      if (iframeRef.current?.contentWindow && event.source !== iframeRef.current.contentWindow) return;
      if (data.type === 'request-plugin-scripts') {
        // [P0-SRCDOC-SLIM] iframe 重建/重载后主动请求插件脚本包 → 强制重推。
        // 源码不再内联进 srcDoc，若此处漏推将导致插件脚本不执行，故忽略版本去重。
        postPluginScriptsToFrame(iframeRef.current?.contentWindow || null, true);
        return;
      }
      if ((data.type === 'diagnostic' || data.type === 'st:diagnostic') && data.diagnostic) {
        onAction?.({ type: 'diagnostic', diagnostic: data.diagnostic });
        return;
      }
      if (data.type === 'resize' && Number.isFinite(data.height)) {
        if (prefersAvailableHeight) {
          updateAvailableHeight();
          return;
        }
        // 内联状态栏：面板自身上报的是真实文档流内容高度，直接采用，不再受视口估算 maxMeasuredHeight
        // 封顶（估算值对含 vh 的 HTML 上限≈0.82 视口，会把展开后的面板截断）。随后统一 clamp 到
        // [INLINE_MIN_HEIGHT, IFRAME_INLINE_MAX_HEIGHT]。
        // [STATUSBAR-HEIGHT] 非内联卡片：若 iframe 上报了 realContent（body 被 vh/fixed 高度裁切了内容，
        // 真实内容高度远超 body 框高），同样不再用视口启发式 maxMeasuredHeight 封顶，否则完整内容会被截断
        // （启发式对含 vh 的 HTML 上限≈0.82 视口，远小于真实内容）。此时直接采用 iframe 上报的真实内容高度。
        const realContentFlag = Number.isFinite(data.realContent) ? Number(data.realContent) : 0;
        const measuredHeight = explicitInline || realContentFlag > 0
          ? Number(data.height)
          : Math.min(Number(data.height), maxMeasuredHeight);
        if (explicitInline) {
          // [STATUSBAR-HEIGHT] postMessage 主通道：双向同步，对齐 ST 内联 DOM + v-if 折叠的
          // “浏览器自然重排”——展开时撑大、收起时收缩都即时生效，杜绝收起后残留空白。
          // 内部 measure() 由 ResizeObserver/MutationObserver 驱动，收起/展开都会触发重新上报，
          // 因此这里不再用 Math.max 限制（旧逻辑只增不减导致收起无法收缩）。
          lastResizeSignalAtRef.current = Date.now();
          const clamped = Math.min(
            Math.max(measuredHeight, INLINE_MIN_HEIGHT),
            IFRAME_INLINE_MAX_HEIGHT,
          );
          setHeight(clamped);
        } else {
          setHeight(Math.max(minMeasuredHeight, measuredHeight));
        }
        return;
      }
      if (data.type === 'frameFocus') {
        frameFocusedEditableRef.current = Boolean(data.focused && data.editable);
        settleViewportContext();
        if (!frameFocusedEditableRef.current && typeof window !== 'undefined') {
          [120, 320, 720, 1200].forEach((delay) => {
            window.setTimeout(() => {
              if (prefersAvailableHeight) {
                updateAvailableHeight();
              } else {
                updateViewportContext();
              }
            }, delay);
          });
        }
        return;
      }
      if (data.type === 'immersiveTheme' && data.theme && typeof data.theme === 'object') {
        setImmersiveTheme((current) => {
          const next = resolveImmersiveTheme(data.theme as SmartCardImmersiveTheme);
          const previous = resolveImmersiveTheme(current);
          if (
            next.backgroundColor === previous.backgroundColor
            && next.foregroundColor === previous.foregroundColor
            && next.isDark === previous.isDark
          ) {
            return current;
          }
          return next;
        });
        return;
      }
      if (data.type === 'setChatMessage' && typeof data.content === 'string') {
        onAction?.({
          type: 'setChatMessage',
          content: data.content,
          index: Number.isFinite(Number(data.index)) ? Number(data.index) : undefined,
          messageId: data.messageId ?? context.messageId ?? null,
          options: data.options && typeof data.options === 'object' ? data.options : undefined,
        });
        return;
      }
      if (data.type === 'st:setChatMessage' && typeof data.content === 'string') {
        onAction?.({
          type: 'setChatMessage',
          content: data.content,
          index: Number.isFinite(Number(data.index)) ? Number(data.index) : undefined,
          messageId: data.messageId ?? context.messageId ?? null,
          options: data.options && typeof data.options === 'object' ? data.options : undefined,
        });
        return;
      }
      const hasDirectActionGesture = data.__palinkUserGesture === true;
      if (data.type === 'sendMessage' && typeof data.content === 'string') {
        if (!hasDirectActionGesture) return;
        onAction?.({ type: 'sendMessage', content: data.content });
        return;
      }
      if (data.type === 'st:sendMessage' && typeof data.content === 'string') {
        if (!hasDirectActionGesture) return;
        onAction?.({ type: 'sendMessage', content: data.content });
        return;
      }
      if (data.type === 'triggerGeneration' || data.type === 'st:triggerGeneration') {
        if (!hasDirectActionGesture) return;
        onAction?.({
          type: 'triggerGeneration',
          content: typeof data.content === 'string' ? data.content : undefined,
          awaitResult: Boolean(data.awaitResult),
        });
        return;
      }
      if (data.type === 'setInputDraft' && typeof data.content === 'string') {
        onAction?.({ type: 'setInputDraft', content: data.content });
        return;
      }
      if (data.type === 'st:setInputDraft' && typeof data.content === 'string') {
        onAction?.({ type: 'setInputDraft', content: data.content });
        return;
      }
      if (data.type === 'request' && typeof data.requestId === 'string' && typeof data.action === 'string') {
        const respond = (response: { ok: boolean; result?: unknown; error?: string }) => {
          iframeRef.current?.contentWindow?.postMessage({
            source: 'palink-smart-card-parent',
            frameId: frameIdRef.current,
            requestId: data.requestId,
            ...response,
          }, '*');
        };
        // [P1-SRCDOC-SLIM] iframe 按需批量拉取插件源码：从完整 bundle 应答。
        // 清单推送只含元数据+URL，内容在此按需下发（父侧内存/HTTP 缓存），
        // 避免每张卡 postMessage 全量传输 ~4.4MB 源码。
        if (data.action === 'getPluginScriptContents') {
          const bundle = getSmartCardPluginScriptBundle();
          const wanted = Array.isArray(data.payload?.scripts) ? data.payload.scripts : [];
          const result: Record<string, string> = {};
          if (bundle && Array.isArray(bundle.scripts)) {
            const contentByKey = new Map<string, string>();
            bundle.scripts.forEach((script) => {
              if (!script || typeof script.content !== 'string') return;
              const key = getSmartCardPluginSourceKey(script.pluginId, script.zip_path || script.path || '');
              contentByKey.set(key, script.content);
            });
            wanted.forEach((item: { pluginId?: string; path?: string } | null | undefined) => {
              if (!item || typeof item !== 'object') return;
              const key = getSmartCardPluginSourceKey(item.pluginId || '', item.path || '');
              const content = contentByKey.get(key);
              if (typeof content === 'string') result[key] = content;
            });
          }
          respond({ ok: true, result });
          return;
        }
        if (onAction) {
          onAction({
            type: 'request',
            requestId: data.requestId,
            action: data.action,
            payload: data.payload && typeof data.payload === 'object' ? data.payload : undefined,
            respond,
          });
        } else {
          respond({ ok: false, error: smartCardText.noActionHandler });
        }
        return;
      }
      if (data.type === 'inspectElement' && data.target) {
        onAction?.({ type: 'inspectElement', target: data.target });
        return;
      }
      if (data.type === 'refresh') {
        onAction?.({ type: 'refresh' });
        return;
      }
      if (data.type === 'scrollChatToBottom' || data.type === 'st:scrollChatToBottom') {
        onAction?.({ type: 'scrollChatToBottom' });
        return;
      }
      if (data.type === 'close' || data.type === 'collapse') {
        onAction?.({ type: 'close' });
        if (!explicitInline && (supportsOuterCollapse || prefersImmersive)) setCollapsed(true);
        return;
      }
      if (data.type === 'storage') {
        applySmartCardStoragePatch(context, sourceFingerprint, data);
        return;
      }
      if (data.type === 'extensionPrompts') {
        // [EP-BRIDGE] iframe 上报的扩展提示词快照 → promptInjection（多 source 聚合）。
        // 完整快照整体替换该 frame 的 source；iframe 卸载时由 unmount cleanup 移除，
        // 避免跨角色/跨卡污染。
        if (data.prompts && typeof data.prompts === 'object') {
          promptInjection.setSourcePrompts(`frame:${frameIdRef.current}`, data.prompts);
        }
        return;
      }
      if (data.type === 'log' || data.type === 'error') {
        onAction?.({ type: data.type, level: data.level, message: data.message });
      }
    };
    window.addEventListener('message', handleMessage);
    return () => window.removeEventListener('message', handleMessage);
  }, [context, maxMeasuredHeight, minMeasuredHeight, onAction, postPluginScriptsToFrame, prefersAvailableHeight, settleViewportContext, smartCardText.noActionHandler, sourceFingerprint, updateAvailableHeight]);

  useEffect(() => {
    if (!prefersImmersive || collapsed || typeof document === 'undefined') return;
    const previousOverflow = document.body.style.overflow;
    const previousOverscroll = document.body.style.overscrollBehavior;
    document.body.style.overflow = 'hidden';
    document.body.style.overscrollBehavior = 'none';
    return () => {
      document.body.style.overflow = previousOverflow;
      document.body.style.overscrollBehavior = previousOverscroll;
    };
  }, [collapsed, prefersImmersive]);

  const toggleTrustedNative = useCallback((event: React.MouseEvent<HTMLButtonElement>) => {
    event.preventDefault();
    event.stopPropagation();
    setPendingTrustAction(trustedNative ? 'revoke' : 'enable');
  }, [trustedNative]);

  const cancelTrustedNative = useCallback((event?: React.MouseEvent<HTMLElement>) => {
    event?.preventDefault();
    event?.stopPropagation();
    setPendingTrustAction(null);
  }, []);

  const confirmTrustedNative = useCallback((event: React.MouseEvent<HTMLButtonElement>) => {
    event.preventDefault();
    event.stopPropagation();
    if (!pendingTrustAction) return;

    const nextTrusted = pendingTrustAction === 'enable';
    writeSmartCardTrustGrant(context.characterId, sourceFingerprint, nextTrusted);
    setTrustedNative(nextTrusted);
    setPendingTrustAction(null);
  }, [context.characterId, pendingTrustAction, sourceFingerprint]);

  // [STATUSBAR-HEIGHT] 状态栏面板兜底：父页面轮询直读 iframe 内容文档的真实高度（同源可访问）。
  // 采用「postMessage 即时同步 + 轮询兜底」双通道，对齐 ST 内联 DOM 的“浏览器自然重排”体验：
  // ① postMessage 是主通道（见 handleMessage 的 resize 分支），双向同步展开/收起高度，即时生效；
  // ② 轮询仅作为兜底——当内部脚本（measure/ResizeObserver/MutationObserver）失效、长时间没有
  //    postMessage resize 上报时才介入，直读真实 scrollHeight 双向同步，避免与主通道互相打架。
  // P2-2（问题 9）: 轮询间隔 160ms→300ms 降频，多卡并存时减小开销；
  //   opaque-origin（P1-1 沙箱隔离后未信任卡）下 contentDocument 不可读，轮询直读无意义，
  //   直接停止轮询（主通道 postMessage 已足够），避免空转。
  const STATUSBAR_POLL_FALLBACK_MS = 800;
  const STATUSBAR_POLL_INTERVAL_MS = 300;
  useEffect(() => {
    if (!explicitInline) return;
    const frame = iframeRef.current;
    if (!frame) return;
    let stopped = false;
    let timer = 0;
    const readFrameHeight = () => {
      if (stopped) return;
      // P2-2（问题 9）: contentDocument 不可读（opaque-origin/跨域）→ 轮询兜底无意义，
      // 停止调度，高度完全依赖 postMessage 主通道。
      try {
        if (!frame.contentDocument) return;
      } catch {
        return;
      }
      // postMessage 主通道活跃（最近 800ms 内收到过 resize 上报）→ 轮询兜底不介入，直接跳过。
      if (Date.now() - lastResizeSignalAtRef.current < STATUSBAR_POLL_FALLBACK_MS) {
        timer = window.setTimeout(readFrameHeight, STATUSBAR_POLL_INTERVAL_MS);
        return;
      }
      let height = 0;
      let fromStored = false;
      try {
        const doc = frame.contentDocument;
        const bodyEl = doc?.body;
        // [STATUSBAR-HEIGHT] 优先直读 iframe measure() 写回的 data-palink-height（已含 +2/vhDriven
        // 处理及 realContent 覆盖），与 postMessage 主通道上报值完全一致。若轮询再用 body.scrollHeight
        // 而主通道用 realContent（被 vh/fixed 裁切时 > body.scrollHeight），两者公式不同会在两值间
        // 周期跳动（轮询改小→触发 ResizeObserver→主通道改大→再轮询改小…），表现为点击后高度抖动。
        const stored = Number(bodyEl?.getAttribute?.('data-palink-height') || 0);
        if (Number.isFinite(stored) && stored > 0) {
          height = stored;
          fromStored = true;
        } else {
          // 属性缺失（iframe 尚未 measure / 脚本失效）时回退到 body 文档流高度。
          height = Math.max(
            bodyEl?.scrollHeight || 0,
            bodyEl?.offsetHeight || 0,
            96,
          );
        }
      } catch { /* not ready yet / cross-origin */ }
      let target = height;
      if (!fromStored) {
        // vh 反馈循环防护（与 iframe 内 measure() 的 vhDriven 判定保持一致）：
        // body 高度由 vh 驱动（body 撑满 iframe 内部视口，即 body.scrollHeight ≈ contentWindow.innerHeight）时，
        // 高度会随 iframe 高度同步增长造成正反馈，必须以上报值本身为稳定基准、不再叠加 +2，切断无限增高。
        let vhDriven = false;
        try {
          const innerH = frame.contentWindow?.innerHeight || 0;
          // [HEIGHT-OSCILLATION-FIX] 与 iframe 内 measure() 的单向 vhDriven 判定保持一致：
          // 内容高度达到/接近视口即视为 vh 驱动，避免双向阈值在两套测量源间翻转形成极限环。
          vhDriven = innerH > 0 && height >= innerH - 4;
        } catch { /* cross-origin */ }
        target = vhDriven ? Math.ceil(height) : Math.ceil(height + 2);
      }
      if (height >= INLINE_MIN_HEIGHT) {
        const clamped = Math.min(
          Math.max(target, INLINE_MIN_HEIGHT),
          IFRAME_INLINE_MAX_HEIGHT,
        );
        setHeight(clamped);
      }
      timer = window.setTimeout(readFrameHeight, STATUSBAR_POLL_INTERVAL_MS);
    };
    timer = window.setTimeout(readFrameHeight, 120);
    return () => {
      stopped = true;
      window.clearTimeout(timer);
    };
    // 注意：依赖数组不能用 iframeKey（它在组件体下方才用 const 声明，
    // 此处若在 deps 里引用会在渲染期触发 TDZ: Cannot access before initialization）。
    // iframeKey 由 effectiveMode + sourceFingerprint + frameIdRef 派生，前两者已足够覆盖重测时机。
  }, [explicitInline, sourceFingerprint, effectiveMode]);

  // P1-1 修复（问题 4）：智能卡 iframe 同源沙箱可逃逸。
  // 此前一律 `allow-scripts allow-same-origin`：同源 iframe 内卡片脚本可直读
  // 父页面 `parent.localStorage`（含 JWT palink_token）/cookie，任意被投毒角色卡
  // （PNG 内嵌 HTML+JS）可窃取会话（浏览器实测警告 "can escape its sandboxing"）。
  // 现在：
  //   - trusted-native（用户显式信任的卡）：保留 allow-same-origin（脚本需读
  //     真实存储/IndexedDB，且信任授予已由 readSmartCardTrustGrant 管控）；
  //   - 其他模式（iframe-js/immersive-sandbox 等）：仅 allow-scripts → opaque
  //     origin，parent/localStorage/cookie 全部不可达；iframe 内存储由
  //     legacy-st-sim 的 memoryStorage 覆盖（postMessage 持久化，不受影响）。
  // 静态 HTML（无脚本）无需 sandbox。
  const sandbox = effectiveMode === 'static-html'
    ? ''
    : trustedNative
      ? 'allow-scripts allow-same-origin'
      : 'allow-scripts';
  const frameHeight = prefersAvailableHeight ? availableHeight : height;
  const frameMinHeight = prefersAvailableHeight ? availableHeight : minMeasuredHeight;
  const iframeKey = `${frameIdRef.current}-${effectiveMode}-${sourceFingerprint}`;
  const showTrustedControl = prefersImmersive && (mode === 'iframe-js' || mode === 'trusted-native');
  const immersiveStableViewportHeight = Math.max(
    IFRAME_AVAILABLE_MIN_HEIGHT,
    Math.round(stableViewportSizeRef.current.height || viewportContext.height || getLayoutViewportHeight()),
  );
  const immersiveViewportStyle = {
    top: 0,
    right: 0,
    bottom: 'auto',
    left: 0,
    width: '100vw',
    height: `${immersiveStableViewportHeight}px`,
    minHeight: `${immersiveStableViewportHeight}px`,
    maxHeight: `${immersiveStableViewportHeight}px`,
    overflow: 'hidden',
    overscrollBehavior: 'none',
    touchAction: 'manipulation',
    background: resolvedImmersiveTheme.backgroundColor,
    transform: 'translateZ(0)',
  } satisfies React.CSSProperties;

  if ((supportsOuterCollapse || prefersImmersive) && collapsed) {
    return (
      <div
        ref={wrapperRef}
        className="relative flex h-11 w-full items-center justify-end bg-background/70"
        data-palink-smart-card-frame={frameIdRef.current}
        data-palink-smart-card-collapsed="true"
      >
        <button
          type="button"
          className="mr-2 inline-flex h-8 w-8 items-center justify-center rounded-full border border-border/70 bg-background/95 text-foreground shadow-sm backdrop-blur transition-colors hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
          title={smartCardText.expand}
          aria-label={smartCardText.expand}
          onClick={(event) => {
            event.preventDefault();
            event.stopPropagation();
            setCollapsed(false);
          }}
        >
          <Maximize2 className="h-4 w-4" aria-hidden="true" />
        </button>
      </div>
    );
  }

  if (prefersImmersive) {
    const immersiveOverlay = (
      <div
        className="fixed"
        style={{ zIndex: 2147483000, ...immersiveViewportStyle }}
        data-palink-smart-card-frame={frameIdRef.current}
        data-palink-smart-card-immersive="true"
        data-palink-smart-card-mode={effectiveMode}
      >
        <iframe
          ref={iframeRef}
          key={iframeKey}
          srcDoc={srcDoc}
          sandbox={sandbox}
          className={cn('absolute h-full w-full border-0', className)}
            style={{
              display: 'block',
              top: 0,
              left: 0,
              height: `${immersiveStableViewportHeight}px`,
              minHeight: `${immersiveStableViewportHeight}px`,
              width: '100vw',
              overflow: 'hidden',
              overscrollBehavior: 'none',
              touchAction: 'manipulation',
              background: resolvedImmersiveTheme.backgroundColor,
              transform: 'translateZ(0)',
            }}
          scrolling="no"
          title={smartCardText.iframeTitle}
          data-palink-smart-card-native={effectiveMode === 'trusted-native' ? 'true' : undefined}
          onLoad={handleFrameLoad}
        />
        <div
          className="pointer-events-none absolute left-2 z-[4] flex flex-col items-center gap-2 opacity-55 transition-opacity hover:opacity-100 focus-within:opacity-100"
          style={{ top: isIOSDevice ? `calc(${immersiveTopInsetPx} + 12px)` : '50%', transform: isIOSDevice ? 'none' : 'translateY(-50%)' }}
        >
          {showTrustedControl && (
            <button
              type="button"
              className="pointer-events-auto inline-flex h-9 w-9 items-center justify-center rounded-full shadow-lg transition-colors focus-visible:outline-none focus-visible:ring-2"
              title={trustedNative ? smartCardText.nativeEnabled : smartCardText.enableNative}
              aria-label={trustedNative ? smartCardText.nativeEnabled : smartCardText.enableNative}
              style={{
                color: immersiveToolbarTextColor,
                background: immersiveToolbarButtonBackground,
                border: `1px solid ${immersiveToolbarButtonBorder}`,
                backdropFilter: immersiveToolbarBackdrop,
                WebkitBackdropFilter: immersiveToolbarBackdrop,
              }}
              onClick={toggleTrustedNative}
            >
              {trustedNative ? (
                <ShieldCheck className="h-4 w-4" aria-hidden="true" />
              ) : (
                <Shield className="h-4 w-4" aria-hidden="true" />
              )}
            </button>
          )}
          <button
            type="button"
            className="pointer-events-auto inline-flex h-9 w-9 items-center justify-center rounded-full shadow-lg transition-colors focus-visible:outline-none focus-visible:ring-2"
            title={smartCardText.close}
            aria-label={smartCardText.close}
            style={{
              color: immersiveToolbarTextColor,
              background: immersiveToolbarButtonBackground,
              border: `1px solid ${immersiveToolbarButtonBorder}`,
              backdropFilter: immersiveToolbarBackdrop,
              WebkitBackdropFilter: immersiveToolbarBackdrop,
            }}
            onClick={(event) => {
              event.preventDefault();
              event.stopPropagation();
              setCollapsed(true);
            }}
          >
            <X className="h-4 w-4" aria-hidden="true" />
          </button>
        </div>
        {pendingTrustAction && (
          <div
            className="absolute inset-0 z-[3] flex items-center justify-center bg-black/55 px-4 backdrop-blur-sm"
            onClick={cancelTrustedNative}
          >
            <div
              role="dialog"
              aria-modal="true"
              aria-labelledby={`${frameIdRef.current}-trust-title`}
              className="w-full max-w-sm rounded-lg border border-white/15 bg-zinc-950/95 p-4 text-white shadow-2xl"
              onClick={(event) => event.stopPropagation()}
            >
              <h2 id={`${frameIdRef.current}-trust-title`} className="text-base font-semibold">
                {pendingTrustAction === 'enable' ? smartCardText.enableNative : smartCardText.revokeNative}
              </h2>
              <p className="mt-3 whitespace-pre-line text-sm leading-6 text-white/75">
                {pendingTrustAction === 'enable'
                  ? smartCardText.enableNativeConfirm
                  : smartCardText.revokeNativeConfirm}
              </p>
              <div className="mt-5 flex justify-end gap-2">
                <button
                  type="button"
                  className="inline-flex h-9 items-center justify-center rounded-md border border-white/15 px-3 text-sm text-white/80 transition-colors hover:bg-white/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white/70"
                  onClick={cancelTrustedNative}
                >
                  {smartCardText.cancel}
                </button>
                <button
                  type="button"
                  className="inline-flex h-9 items-center justify-center rounded-md bg-white px-3 text-sm font-medium text-zinc-950 transition-colors hover:bg-white/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white/70"
                  onClick={confirmTrustedNative}
                >
                  {smartCardText.confirm}
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    );

    return (
      <>
        <div
          ref={wrapperRef}
          className="relative h-0 w-full overflow-visible"
          data-palink-smart-card-frame={frameIdRef.current}
          data-palink-smart-card-placeholder="true"
        />
        {typeof document !== 'undefined' ? createPortal(immersiveOverlay, document.body) : immersiveOverlay}
      </>
    );
  }

  return (
    <div ref={wrapperRef} className="relative w-full" data-palink-smart-card-frame={frameIdRef.current}>
      {supportsOuterCollapse && (
        <button
          type="button"
          className="absolute right-2 top-2 z-20 inline-flex h-8 w-8 items-center justify-center rounded-full border border-white/25 bg-black/35 text-white shadow-lg backdrop-blur transition-colors hover:bg-black/55 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white/80"
          title={smartCardText.collapse}
          aria-label={smartCardText.collapse}
          onClick={(event) => {
            event.preventDefault();
            event.stopPropagation();
            setCollapsed(true);
          }}
        >
          <X className="h-4 w-4" aria-hidden="true" />
        </button>
      )}
      <iframe
        ref={iframeRef}
        key={iframeKey}
        srcDoc={srcDoc}
        sandbox={sandbox}
        className={cn('w-full border-0 bg-transparent', className)}
        style={{
          display: 'block',
          height: `${frameHeight}px`,
          minHeight: `${frameMinHeight}px`,
          maxHeight: prefersAvailableHeight ? `${frameHeight}px` : undefined,
          overflow: 'hidden',
          // P1-3（问题 2）: 内联 iframe 与沉浸式分支一致启用 touch-action: manipulation，
          // 避免 iOS 上 iframe 触摸与外层聊天滚动冲突；内容超高（高度测量失效）时
          // 由 iframe 内 body overflow-y:auto 提供内部滚动兜底（wrapHtmlFragment）。
          touchAction: 'manipulation',
        }}
        scrolling="no"
        title={smartCardText.iframeTitle}
        onLoad={handleFrameLoad}
      />
    </div>
  );
});

interface InlineHtmlRendererProps {
  html: string;
  customCss?: string;
  className?: string;
}

export const InlineHtmlRenderer = React.memo(function InlineHtmlRenderer({
  html,
  customCss,
  className,
}: InlineHtmlRendererProps) {
  const inlineIdRef = useRef(`palink-inline-card-${Math.random().toString(36).slice(2)}-${Date.now()}`);
  const scopedHtml = useMemo(
    () => prepareInlineHtml(html, `[data-palink-inline-card="${inlineIdRef.current}"]`, customCss),
    [html, customCss]
  );

  return (
    <div
      className={cn('palink-inline-card w-full max-w-full overflow-visible', className)}
      data-palink-inline-card={inlineIdRef.current}
      dangerouslySetInnerHTML={{ __html: scopedHtml }}
    />
  );
});

interface CharacterCardRendererProps {
  content: string;
  customCss?: string;
  className?: string;
  context?: CharacterSmartCardContext;
  mode?: SmartCardRenderMode;
  onAction?: (action: SmartCardAction) => void;
  renderRemaining?: (remaining: string) => React.ReactNode;
}

function buildSmartCardImmersiveBridge(frameId: string): string {
  const frameIdJson = safeJson(frameId);
  return `
<script nonce="${SMART_CARD_CSP_NONCE}">
(() => {
  const frameId = ${frameIdJson};
  const post = (payload) => {
    try {
      window.parent.postMessage({ source: 'palink-smart-card', frameId, ...payload }, '*');
    } catch {}
  };
  const colorPattern = /(?:^rgba?\\(|^#|rgba?\\(|#[0-9a-f]{3,8}\\b)/i;
  const transparentPattern = /^transparent$/i;
  const alphaOfColor = (value) => {
    const alphaMatch = String(value || '').trim().match(/^rgba?\\(\\s*[^)]*?(?:,|\\/)\\s*([0-9.]+%?)\\s*\\)$/i);
    if (!alphaMatch) return 1;
    const alpha = alphaMatch[1].endsWith('%') ? Number(alphaMatch[1].slice(0, -1)) / 100 : Number(alphaMatch[1]);
    return Number.isFinite(alpha) ? alpha : 1;
  };
  const normalizeColor = (value) => {
    const source = String(value || '').trim();
    if (!source || transparentPattern.test(source)) return '';
    const colorMatches = source.match(/rgba?\\([^)]*\\)|#[0-9a-f]{3,8}\\b/gi) || [];
    for (const color of colorMatches) {
      if (alphaOfColor(color) > 0.05) return color;
    }
    return colorPattern.test(source) ? source : '';
  };
  const isVisibleElement = (element) => {
    if (!element || element === document.documentElement) return false;
    const rect = element.getBoundingClientRect?.();
    if (!rect || rect.width < 8 || rect.height < 8) return false;
    const style = window.getComputedStyle(element);
    return style.display !== 'none' && style.visibility !== 'hidden' && Number(style.opacity || 1) > 0.05;
  };
  const colorsFromElement = (element) => {
    const results = [];
    let current = element;
    let depth = 0;
    while (current && depth < 8) {
      if (current.nodeType !== Node.ELEMENT_NODE) {
        current = current.parentElement;
        depth += 1;
        continue;
      }
      const style = window.getComputedStyle(current);
      const backgroundColor = normalizeColor(style.backgroundColor);
      const backgroundImage = normalizeColor(style.backgroundImage);
      if (backgroundColor) results.push(backgroundColor);
      if (backgroundImage) results.push(backgroundImage);
      current = current.parentElement;
      depth += 1;
    }
    return results;
  };
  const visibleSampleElements = () => {
    const width = Math.max(1, window.innerWidth || document.documentElement.clientWidth || 1);
    const height = Math.max(1, window.innerHeight || document.documentElement.clientHeight || 1);
    const points = [
      [width * 0.5, 16],
      [width * 0.5, Math.max(24, height * 0.08)],
      [width * 0.25, Math.max(32, height * 0.12)],
      [width * 0.75, Math.max(32, height * 0.12)],
      [width * 0.5, height * 0.24],
    ];
    const seen = new Set();
    const elements = [];
    for (const [rawX, rawY] of points) {
      const x = Math.max(1, Math.min(width - 1, Math.round(rawX)));
      const y = Math.max(1, Math.min(height - 1, Math.round(rawY)));
      let element = document.elementFromPoint(x, y);
      while (element && !isVisibleElement(element)) element = element.parentElement;
      if (element && !seen.has(element)) {
        seen.add(element);
        elements.push(element);
      }
    }
    return elements;
  };
  const readTheme = () => {
    const root = document.documentElement;
    const body = document.body;
    const candidates = [
      ...visibleSampleElements(),
      document.querySelector('[class*="container"]'),
      document.querySelector('[class*="wrapper"]'),
      document.querySelector('[id*="container"]'),
      document.querySelector('[id*="wrapper"]'),
      document.querySelector('main'),
      body,
      root,
    ]
      .filter(Boolean);
    let backgroundColor = '';
    let foregroundColor = '';
    for (const element of candidates) {
      const style = window.getComputedStyle(element);
      if (!backgroundColor) {
        backgroundColor = colorsFromElement(element).find(Boolean) || '';
      }
      if (!foregroundColor && style.color && colorPattern.test(style.color)) {
        foregroundColor = normalizeColor(style.color);
      }
      if (backgroundColor && foregroundColor) break;
    }
    const bodyStyle = body ? window.getComputedStyle(body) : null;
    const rootStyle = root ? window.getComputedStyle(root) : null;
    const resolvedBackground = backgroundColor || normalizeColor(bodyStyle?.backgroundColor) || normalizeColor(rootStyle?.backgroundColor) || '';
    const resolvedForeground = foregroundColor || normalizeColor(bodyStyle?.color) || normalizeColor(rootStyle?.color) || '';
    post({
      type: 'immersiveTheme',
      theme: {
        backgroundColor: resolvedBackground,
        foregroundColor: resolvedForeground,
      },
    });
  };
  const scheduleReadTheme = (() => {
    let rafId = 0;
    return () => {
      if (rafId) cancelAnimationFrame(rafId);
      rafId = requestAnimationFrame(() => {
        rafId = 0;
        readTheme();
      });
    };
  })();
  window.addEventListener('load', scheduleReadTheme, { once: true });
  window.addEventListener('resize', scheduleReadTheme);
  document.addEventListener('DOMContentLoaded', scheduleReadTheme, { once: true });
  const observer = typeof MutationObserver !== 'undefined'
    ? new MutationObserver(scheduleReadTheme)
    : null;
  observer?.observe(document.documentElement, {
    subtree: true,
    attributes: true,
    childList: true,
    attributeFilter: ['class', 'style'],
  });
  scheduleReadTheme();
})();
</script>`;
}

function CharacterCardRendererInner({
  content,
  customCss,
  className,
  context = {},
  mode = 'auto',
  onAction,
  renderRemaining,
}: CharacterCardRendererProps) {
  const renderParts = useMemo(() => extractHtmlRenderParts(content), [content]);

  if (typeof window !== 'undefined') {
    try {
      (window as any).__dbgContent = content;
      (window as any).__dbgParts = (renderParts || []).map(p => ({ type: p.type, len: p.content.length, full: p.content }));
    } catch { /* ignore */ }
  }

  if (renderParts) {
    const signatureLastIndex = new Map<string, number>();
    renderParts.forEach((part, index) => {
      if (part.type === 'html') signatureLastIndex.set(getHtmlRenderSignature(part.content), index);
    });
    const seenHtml = new Set<string>();

    return (
      <div className={cn('character-card-renderer w-full', className)} data-palink-smart-card="true">
        {renderParts.map((part, index) => {
          if (part.type === 'markdown') {
            return renderRemaining ? (
              <React.Fragment key={`markdown-${index}`}>
                {renderRemaining(part.content)}
              </React.Fragment>
            ) : (
              <div key={`markdown-${index}`} className="markdown-content w-full whitespace-pre-wrap break-words">
                <ReactMarkdown
                  remarkPlugins={REMAINING_MARKDOWN_PLUGINS}
                  rehypePlugins={REMAINING_REHYPE_PLUGINS}
                >
                  {part.content}
                </ReactMarkdown>
              </div>
            );
          }

          const html = part.content;
          const signature = getHtmlRenderSignature(html);
          if (signatureLastIndex.get(signature) !== index) return null;
          const htmlKey = html.trim().replace(/\s+/g, ' ');
          if (!htmlKey || seenHtml.has(htmlKey)) return null;
          seenHtml.add(htmlKey);
          const resolvedMode = resolveHtmlRenderMode(html, mode);
          if (resolvedMode === 'inline-html') {
            return (
              <InlineHtmlRenderer
                key={`html-${index}`}
                html={html}
                customCss={customCss}
              />
            );
          }
          return (
            <IframeRenderer
              key={`html-${index}`}
              html={html}
              isFullDocument={isFullHtmlDocument(html)}
              customCss={customCss}
              context={context}
              mode={resolvedMode}
              onAction={onAction}
            />
          );
        })}
      </div>
    );
  }

  return (
    <div className={cn('markdown-content w-full whitespace-pre-wrap break-words', className)}>
      {content}
    </div>
  );
}

export const CharacterCardRenderer = React.memo(CharacterCardRendererInner);

