// AUTO-GENERATED by scripts/_p1-split.mjs (P1 机械拆分，逻辑未改动)
// 源: src/components/ui/custom/CharacterCardRenderer.tsx
import remarkGfm from 'remark-gfm';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import { api } from '@/services/api';
import type { CharacterSmartCardContext, Language, SillyTavernPluginRuntimeConfig, SmartCardCompatDiagnostic } from '@/types';

export const HTML_CODE_BLOCK_PATTERN = /(`{3,})html\s*\r?\n([\s\S]*?)\r?\n`{3,}\s*(?:\$[0-9]+\s*)?(?=\r?\n|$)/g;
export const OPEN_HTML_CODE_BLOCK_PATTERN = /(^|\n)(`{3,})html\s*\r?\n([\s\S]*)$/i;
export const FULL_HTML_START_PATTERN = /(?:^|\n)\s*(?:html\s*)?(?:<!DOCTYPE\s+html|<html[\s>])/i;
export const REMAINING_MARKDOWN_PLUGINS = [remarkGfm, remarkMath];
export const REMAINING_REHYPE_PLUGINS = [rehypeKatex];
export const INLINE_MIN_HEIGHT = 32;
export const IFRAME_DEFAULT_HEIGHT = 220;
export const IFRAME_MAX_HEIGHT = 5000;
export const IFRAME_INLINE_MAX_HEIGHT = IFRAME_MAX_HEIGHT;
export const IFRAME_VIEWPORT_MIN_HEIGHT = 320;
export const IFRAME_VIEWPORT_MAX_INITIAL_HEIGHT = 680;
export const IFRAME_VIEWPORT_RATIO = 0.68;
export const IFRAME_VIEWPORT_MAX_RATIO = 0.82;
export const IFRAME_VIEWPORT_BOTTOM_GAP = 8;
export const IFRAME_VIEWPORT_FALLBACK_BOTTOM_RESERVED = 132;
export const IFRAME_AVAILABLE_MIN_HEIGHT = 96;
export const SMART_CARD_PRECONNECT_LIMIT = 4;
export const SMART_CARD_HIGH_RESOURCE_LIMIT = 6;
export const SMART_CARD_HIGH_STYLE_LIMIT = 2;
export const SMART_CARD_HIGH_IMAGE_LIMIT = 2;
export const SMART_CARD_HIGH_FONT_LIMIT = 3;
export const SMART_CARD_DEFERRED_RESOURCE_LIMIT = 32;
export const SMART_CARD_HIGH_RESOURCE_DELAY_MS = 0;
export const SMART_CARD_DEFERRED_START_DELAY_MS = 900;
export const SMART_CARD_DEFERRED_RESOURCE_DELAY_MS = 80;
export const SMART_CARD_RESOURCE_WARM_TIMEOUT_MS = 15000;
export const SMART_CARD_ASSET_PROXY_ENDPOINT = '/api/smart-card-assets?url=';
export const SMART_CARD_ASSET_PREFETCH_ENDPOINT = '/api/smart-card-assets/prefetch';
export const SMART_CARD_IFRAME_IMAGE_INITIAL_LOAD_COUNT = 3;
export const SMART_CARD_IFRAME_IMAGE_QUEUE_DELAY_MS = 120;
export const SMART_CARD_RENDER_CACHE_LIMIT = 32;
export const SMART_CARD_CSP_NONCE = 'palink-smart-card';
export const SMART_CARD_TRUST_STORAGE_PREFIX = 'palink-smart-card-trust:';
export const SMART_CARD_TRUST_SESSION_TTL_MS = 30 * 60 * 1000;
export const SMART_CARD_CONTEXT_FULL_MESSAGE_LIMIT = 96;
export const SMART_CARD_CONTEXT_HEAD_MESSAGE_COUNT = 3;
export const SMART_CARD_CONTEXT_RECENT_MESSAGE_COUNT = 64;
export const SMART_CARD_CONTEXT_ANCHOR_RADIUS = 6;
export const SMART_CARD_CONTEXT_UPDATE_DELAY_MS = 80;
export const SMART_CARD_VIEWPORT_SETTLE_DELAYS_MS = [0, 80, 180, 360, 700];
export const smartCardWarmedResources = new Set<string>();
export const smartCardHintedOrigins = new Set<string>();
export const smartCardPrefetchedAssetUrls = new Set<string>();
export const smartCardResourcePlanCache = new Map<string, SmartCardResourcePlan>();
export const smartCardOptimizedHtmlCache = new Map<string, string>();
export const smartCardAdaptedHtmlCache = new Map<string, string>();
export const smartCardNormalizedScriptCache = new Map<string, string>();
export const smartCardAdapterStyleCache = new Map<string, string>();

export const SMART_CARD_UI_TEXT: Record<Language, {
  expand: string;
  collapse: string;
  close: string;
  iframeTitle: string;
  nativeEnabled: string;
  enableNative: string;
  revokeNative: string;
  revokeNativeConfirm: string;
  enableNativeConfirm: string;
  requestTimeout: string;
  requestFailed: string;
  noActionHandler: string;
  cancel: string;
  confirm: string;
  contrastAdjustedBadge: string;
  contrastAdjustedBadgeClose: string;
}> = {
  zh: {
    expand: '展开角色卡',
    collapse: '收起角色卡',
    close: '关闭角色卡',
    iframeTitle: '角色卡',
    nativeEnabled: 'Tavern 原生模式已启用',
    enableNative: '启用 Tavern 原生模式',
    revokeNative: '撤销 Tavern 原生模式',
    revokeNativeConfirm: '要撤销这张角色卡的 Tavern 原生模式授权吗？',
    enableNativeConfirm:
      '要为这张角色卡临时启用 Tavern 原生模式吗？\n\n这会允许角色卡访问父页面 DOM，以获得最高兼容性。授权只在当前浏览器会话短期有效，请只为你信任的角色卡启用。',
    requestTimeout: '角色卡兼容请求超时',
    requestFailed: '角色卡兼容请求失败',
    noActionHandler: '当前没有可用的角色卡动作处理器。',
    cancel: '取消',
    confirm: '确认',
    contrastAdjustedBadge: '已优化 {n} 处低对比文字，暗色模式显示原始样式',
    contrastAdjustedBadgeClose: '关闭',
  },
  en: {
    expand: 'Expand smart card',
    collapse: 'Collapse smart card',
    close: 'Close smart card',
    iframeTitle: 'Character Card',
    nativeEnabled: 'Native Tavern mode enabled',
    enableNative: 'Enable native Tavern mode',
    revokeNative: 'Revoke native Tavern mode',
    revokeNativeConfirm: 'Revoke native Tavern mode for this character card?',
    enableNativeConfirm:
      'Temporarily enable native Tavern mode for this character card?\n\nThis lets the card access the parent page DOM for maximum compatibility. The grant only lasts for this browser session. Only enable it for cards you trust.',
    requestTimeout: 'Palink smart card request timed out',
    requestFailed: 'Palink smart card request failed',
    noActionHandler: 'No Palink smart card action handler is available.',
    cancel: 'Cancel',
    confirm: 'Confirm',
    contrastAdjustedBadge: 'Adjusted {n} low-contrast text(s); original colors show in dark mode',
    contrastAdjustedBadgeClose: 'Dismiss',
  },
};

SMART_CARD_UI_TEXT.zh = {
  expand: '展开角色卡',
  collapse: '收起角色卡',
  close: '关闭角色卡',
  iframeTitle: '角色卡',
  nativeEnabled: 'Tavern 原生模式已启用',
  enableNative: '启用 Tavern 原生模式',
  revokeNative: '撤销 Tavern 原生模式',
  revokeNativeConfirm: '要撤销这张角色卡的 Tavern 原生模式授权吗？',
  enableNativeConfirm:
    '要为这张角色卡临时启用 Tavern 原生模式吗？\n\n这会允许角色卡访问父页面 DOM，以获得最高兼容性。授权只在当前浏览器会话短期有效，请只为你信任的角色卡启用。',
  requestTimeout: '角色卡兼容请求超时',
  requestFailed: '角色卡兼容请求失败',
  noActionHandler: '当前没有可用的角色卡动作处理器。',
  cancel: '取消',
  confirm: '确认',
  contrastAdjustedBadge: '已优化 {n} 处低对比文字，暗色模式显示原始样式',
  contrastAdjustedBadgeClose: '关闭',
};

Object.assign(SMART_CARD_UI_TEXT.zh, {
  expand: '\u5c55\u5f00\u89d2\u8272\u5361',
  collapse: '\u6536\u8d77\u89d2\u8272\u5361',
  close: '\u5173\u95ed\u89d2\u8272\u5361',
  iframeTitle: '\u89d2\u8272\u5361',
  nativeEnabled: 'Tavern \u539f\u751f\u6a21\u5f0f\u5df2\u542f\u7528',
  enableNative: '\u542f\u7528 Tavern \u539f\u751f\u6a21\u5f0f',
  revokeNative: '\u64a4\u9500 Tavern \u539f\u751f\u6a21\u5f0f',
  revokeNativeConfirm: '\u8981\u64a4\u9500\u8fd9\u5f20\u89d2\u8272\u5361\u7684 Tavern \u539f\u751f\u6a21\u5f0f\u6388\u6743\u5417\uff1f',
  enableNativeConfirm:
    '\u8981\u4e3a\u8fd9\u5f20\u89d2\u8272\u5361\u4e34\u65f6\u542f\u7528 Tavern \u539f\u751f\u6a21\u5f0f\u5417\uff1f\n\n\u8fd9\u4f1a\u5141\u8bb8\u89d2\u8272\u5361\u8bbf\u95ee\u7236\u9875\u9762 DOM\uff0c\u4ee5\u83b7\u5f97\u6700\u9ad8\u517c\u5bb9\u6027\u3002\u6388\u6743\u53ea\u5728\u5f53\u524d\u6d4f\u89c8\u5668\u4f1a\u8bdd\u77ed\u671f\u6709\u6548\uff0c\u8bf7\u53ea\u4e3a\u4f60\u4fe1\u4efb\u7684\u89d2\u8272\u5361\u542f\u7528\u3002',
  requestTimeout: '\u89d2\u8272\u5361\u517c\u5bb9\u8bf7\u6c42\u8d85\u65f6',
  requestFailed: '\u89d2\u8272\u5361\u517c\u5bb9\u8bf7\u6c42\u5931\u8d25',
  noActionHandler: '\u5f53\u524d\u6ca1\u6709\u53ef\u7528\u7684\u89d2\u8272\u5361\u52a8\u4f5c\u5904\u7406\u5668\u3002',
  cancel: '\u53d6\u6d88',
  confirm: '\u786e\u8ba4',
});

export type IframeRenderMode = 'iframe-js' | 'static-html' | 'trusted-native';
export type SmartCardResourceKind = 'image' | 'style' | 'script' | 'font' | 'other';
export type SmartCardImmersiveTheme = {
  backgroundColor?: string;
  foregroundColor?: string;
  isDark?: boolean;
};
export type SmartCardViewportContext = NonNullable<CharacterSmartCardContext['viewport']>;
export type SmartCardRenderPart =
  | { type: 'html'; content: string }
  | { type: 'markdown'; content: string };

export interface SmartCardResource {
  url: string;
  sourceUrl: string;
  kind: SmartCardResourceKind;
  priority: 'high' | 'deferred';
  index: number;
}

export interface SmartCardResourcePlan {
  preconnectOrigins: string[];
  high: SmartCardResource[];
  deferred: SmartCardResource[];
}

export interface RgbaColor {
  r: number;
  g: number;
  b: number;
  a: number;
}

export interface SmartCardInspectTarget {
  id: string;
  tag: string;
  text: string;
  selector: string;
  role?: string;
  rect: {
    x: number;
    y: number;
    width: number;
    height: number;
  };
}

export type SmartCardAction =
  | { type: 'sendMessage'; content: string }
  | { type: 'triggerGeneration'; content?: string; awaitResult?: boolean }
  | { type: 'close' }
  | { type: 'setChatMessage'; content: string; index?: number; messageId?: string | number | null; options?: Record<string, unknown> }
  | { type: 'setInputDraft'; content: string }
  | { type: 'scrollChatToBottom' }
  | {
      type: 'request';
      requestId: string;
      action: string;
      payload?: Record<string, unknown>;
      respond: (response: { ok: boolean; result?: unknown; error?: string }) => void;
    }
  | { type: 'diagnostic'; diagnostic: SmartCardCompatDiagnostic }
  | { type: 'refresh' }
  | { type: 'inspectElement'; target: SmartCardInspectTarget }
  | { type: 'log'; level?: string; message?: string }
  | { type: 'error'; message?: string };
